#!/usr/bin/env python3
#
# 2019年 10月 13日 星期日 00:00:33 CST

from widgets import wx, btn, cb, cbb, ci, nc, sl, sp, st, tc


class Model(object):
  def __init__(self, full = True):
    self._core()

    if full:
      self._outer()

  def _outer(self):
    pass
  # 目标url - burp日志 - HTTP请求...
    self._url_combobox = cbb()
    self._burp_logfile = tc()
    self._burp_logfile_chooser = btn()
    self._request_file = tc()
    self._request_file_chooser = btn()
    self._bulkfile = tc()
    self._bulkfile_chooser = btn()
    self._configfile = tc()
    self._configfile_chooser = btn()
    self._sitemap_url = tc()
    self._google_dork = tc()
  # 选项区(1)
  # sqlmap命令语句:
    self._cmd_entry = tc()
  # self._core()...
  # 输出区(2)
  # 日志区(3)
    self._page3_log_view = tc()
    self._page3_read_target_btn = btn()
    self._page3_clear_btn = btn()
    self._page3_read_log_btn = btn()
  # API区(4)
    self._page4_api_server_label = st()
    self._page4_api_server_entry = tc()
    self._page4_admin_token_label = st()
    self._page4_admin_token_entry = tc()
    self._page4_task_new_btn = btn()
    self._page4_admin_list_btn = btn()
    self._page4_admin_flush_btn = btn()
    self._page4_clear_task_view_btn = btn()
    self._page4_username_label = st()
    self._page4_username_entry = tc()
    self._page4_password_label = st()
    self._page4_password_entry = tc()
    self._page4_option_get_entry = tc()
    self._page4_option_set_view = tc()
    self._page4_task_view = tc()
  # 帮助(H)
    self._page5_manual_view = tc()

  def _core(self):
    pass
  # 测试(Q)
    self._sqlmap_path_label = st()
    self.sqlmap_path_entry = tc()
    self._sqlmap_path_chooser = btn()
    # 注入选项
    self._inject_area = wx.StaticBox()
    self._inject_area_param_ckbtn = cb()
    self._inject_area_param_entry = tc()
    self._inject_area_param_filter_ckbtn = cb()
    self._inject_area_param_filter_combobox = cbb()
    self._inject_area_skip_static_ckbtn = cb()
    self._inject_area_skip_ckbtn = cb()
    self._inject_area_skip_entry = tc()
    self._inject_area_param_exclude_ckbtn = cb()
    self._inject_area_param_exclude_entry = tc()
    self._inject_area_prefix_ckbtn = cb()
    self._inject_area_prefix_entry = tc()
    self._inject_area_suffix_ckbtn = cb()
    self._inject_area_suffix_entry = tc()
    self._inject_area_dbms_ckbtn = cb()
    self._inject_area_dbms_combobox = cbb()
    self._inject_area_dbms_cred_ckbtn = cb()
    self._inject_area_dbms_cred_entry = tc()
    self._inject_area_os_ckbtn = cb()
    self._inject_area_os_entry = tc()
    self._inject_area_no_cast_ckbtn = cb()
    self._inject_area_no_escape_ckbtn = cb()
    self._inject_area_invalid_logic_ckbtn = cb()
    self._inject_area_invalid_bignum_ckbtn = cb()
    self._inject_area_invalid_str_ckbtn = cb()
    # 探测选项
    self._detection_area = wx.StaticBox()
    self._detection_area_level_ckbtn = cb()
    self._detection_area_level_scale = sl()
    self._detection_area_risk_ckbtn = cb()
    self._detection_area_risk_scale = sl()
    self._detection_area_str_ckbtn = cb()
    self._detection_area_str_entry = tc()
    self._detection_area_not_str_ckbtn = cb()
    self._detection_area_not_str_entry = tc()
    self._detection_area_re_ckbtn = cb()
    self._detection_area_re_entry = tc()
    self._detection_area_code_ckbtn = cb()
    self._detection_area_code_entry = nc()
    self._detection_area_text_only_ckbtn = cb()
    self._detection_area_titles_ckbtn = cb()
    self._detection_area_smart_ckbtn = cb()
    # 各注入技术的选项
    self._tech_area = wx.StaticBox()
    self._tech_area_tech_ckbtn = cb()
    self._tech_area_tech_entry = tc()
    self._tech_area_time_sec_ckbtn = cb()
    self._tech_area_time_sec_entry = nc()
    self._tech_area_union_col_ckbtn = cb()
    self._tech_area_union_col_entry = nc()
    self._tech_area_union_char_ckbtn = cb()
    self._tech_area_union_char_entry = tc()
    self._tech_area_union_from_ckbtn = cb()
    self._tech_area_union_from_entry = tc()
    self._tech_area_dns_ckbtn = cb()
    self._tech_area_dns_entry = tc()
    self._tech_area_second_url_ckbtn = cb()
    self._tech_area_second_url_entry = tc()
    self._tech_area_second_req_ckbtn = cb()
    self._tech_area_second_req_entry = tc()
    self._tech_area_second_req_chooser = btn()
    # tamper脚本
    self._tamper_area = wx.StaticBox()
    self._tamper_area_tamper_view = tc()
    # 性能优化
    self._optimize_area = wx.StaticBox()
    self._optimize_area_turn_all_ckbtn = cb()
    self._optimize_area_thread_num_ckbtn = cb()
    self._optimize_area_thread_num_spinbtn = sp()
    self._optimize_area_predict_ckbtn = cb()
    self._optimize_area_keep_alive_ckbtn = cb()
    self._optimize_area_null_connect_ckbtn = cb()
    # 常用选项
    self._general_area = wx.StaticBox()
    self._general_area_verbose_ckbtn = cb()
    self._general_area_verbose_scale = sl()
    self._general_area_finger_ckbtn = cb()
    self._general_area_hex_ckbtn = cb()
    self._general_area_batch_ckbtn = cb()
    self._page1_misc_wizard_ckbtn = cb()
  # 请求(W)
    # HTTP header
    self._request_header_area = wx.StaticBox()
    self._request_area_random_agent_ckbtn = cb()
    self._request_area_mobile_ckbtn = cb()
    self._request_area_user_agent_ckbtn = cb()
    self._request_area_user_agent_entry = tc()
    self._request_area_host_ckbtn = cb()
    self._request_area_host_entry = tc()
    self._request_area_referer_ckbtn = cb()
    self._request_area_referer_entry = tc()
    self._request_area_header_ckbtn = cb()
    self._request_area_header_entry = tc()
    self._request_area_headers_ckbtn = cb()
    self._request_area_headers_entry = tc()
    # HTTP data
    self._request_data_area = wx.StaticBox()
    self._request_area_method_ckbtn = cb()
    self._request_area_method_entry = tc()
    self._request_area_param_del_ckbtn = cb()
    self._request_area_param_del_entry = tc()
    self._request_area_chunked_ckbtn = cb()
    self._request_area_post_ckbtn = cb()
    self._request_area_post_entry = tc()
    self._request_area_cookie_ckbtn = cb()
    self._request_area_cookie_entry = tc()
    self._request_area_cookie_del_ckbtn = cb()
    self._request_area_cookie_del_entry = tc()
    self._request_area_load_cookies_ckbtn = cb()
    self._request_area_load_cookies_entry = tc()
    self._request_area_load_cookies_chooser = btn()
    self._request_area_drop_set_cookie_ckbtn = cb()
    self._request_area_auth_type_ckbtn = cb()
    self._request_area_auth_type_entry = tc()
    self._request_area_auth_cred_ckbtn = cb()
    self._request_area_auth_cred_entry = tc()
    self._request_area_auth_file_ckbtn = cb()
    self._request_area_auth_file_entry = tc()
    self._request_area_auth_file_chooser = btn()
    self._request_area_csrf_method_ckbtn = cb()
    self._request_area_csrf_method_entry = tc()
    self._request_area_csrf_token_ckbtn = cb()
    self._request_area_csrf_token_entry = tc()
    self._request_area_csrf_url_ckbtn = cb()
    self._request_area_csrf_url_entry = tc()
    # request定制
    self._request_custom_area = wx.StaticBox()
    self._request_area_ignore_timeouts_ckbtn = cb()
    self._request_area_ignore_redirects_ckbtn = cb()
    self._request_area_ignore_code_ckbtn = cb()
    self._request_area_ignore_code_entry = tc()
    self._request_area_skip_urlencode_ckbtn = cb()
    self._request_area_force_ssl_ckbtn = cb()
    self._request_area_hpp_ckbtn = cb()
    self._request_area_delay_ckbtn = cb()
    self._request_area_delay_entry = nc()
    self._request_area_timeout_ckbtn = cb()
    self._request_area_timeout_entry = nc()
    self._request_area_retries_ckbtn = cb()
    self._request_area_retries_entry = nc()
    self._request_area_randomize_ckbtn = cb()
    self._request_area_randomize_entry = tc()
    self._request_area_eval_ckbtn = cb()
    self._request_area_eval_entry = tc()
    # 隐匿/代理
    self._request_proxy_area = wx.StaticBox()
    self._request_area_safe_url_ckbtn = cb()
    self._request_area_safe_url_entry = tc()
    self._request_area_safe_post_ckbtn = cb()
    self._request_area_safe_post_entry = tc()
    self._request_area_safe_req_ckbtn = cb()
    self._request_area_safe_req_entry = tc()
    self._request_area_safe_req_chooser = btn()
    self._request_area_safe_freq_ckbtn = cb()
    self._request_area_safe_freq_entry = tc()
    self._request_area_ignore_proxy_ckbtn = cb()
    self._request_area_proxy_ckbtn = cb()
    self._request_area_proxy_file_ckbtn = cb()
    self._request_area_proxy_file_entry = tc()
    self._request_area_proxy_file_chooser = btn()
    self._request_area_proxy_ip_label = st()
    self._request_area_proxy_ip_entry = tc()
    self._request_area_proxy_port_label = st()
    self._request_area_proxy_port_entry = nc()
    self._request_area_proxy_username_label = st()
    self._request_area_proxy_username_entry = tc()
    self._request_area_proxy_password_label = st()
    self._request_area_proxy_password_entry = tc()
    self._request_area_tor_ckbtn = cb()
    self._request_area_tor_port_ckbtn = cb()
    self._request_area_tor_port_entry = nc()
    self._request_area_tor_type_ckbtn = cb()
    self._request_area_tor_type_entry = tc()
    self._request_area_check_tor_ckbtn = cb()
  # 枚举(E)
    # 枚举
    self._enum_area = wx.StaticBox()
    # 要求要与_enum_area_enum_labels的结构一致!
    self._enum_area_opts_ckbtns = [[cb() for _ in range(5)] for _r in range(3)]
    # Dump(转储)
    self._dump_area = wx.StaticBox()
    self._dump_area_dump_ckbtn = cb()
    self._dump_area_repair_ckbtn = cb()
    self._dump_area_statements_ckbtn = cb()
    self._dump_area_search_ckbtn = cb()
    self._dump_area_no_sys_db_ckbtn = cb()
    self._dump_area_dump_all_ckbtn = cb()
    # limit(dump时的限制)
    self._limit_area = wx.StaticBox()
    self._limit_area_start_ckbtn = cb()
    self._limit_area_start_entry = nc()
    self._limit_area_stop_ckbtn = cb()
    self._limit_area_stop_entry = nc()
    # 盲注选项
    self._blind_area = wx.StaticBox()
    self._blind_area_first_ckbtn = cb()
    self._blind_area_first_entry = nc()
    self._blind_area_last_ckbtn = cb()
    self._blind_area_last_entry = nc()
    # 数据库名, 表名, 列名...
    self._meta_area = wx.StaticBox()
    self._meta_area_D_ckbtn = cb()
    self._meta_area_D_entry = tc()
    self._meta_area_T_ckbtn = cb()
    self._meta_area_T_entry = tc()
    self._meta_area_C_ckbtn = cb()
    self._meta_area_C_entry = tc()
    self._meta_area_U_ckbtn = cb()
    self._meta_area_U_entry = tc()
    self._meta_area_X_ckbtn = cb()
    self._meta_area_X_entry = tc()
    self._meta_area_pivot_ckbtn = cb()
    self._meta_area_pivot_entry = tc()
    self._meta_area_where_ckbtn = cb()
    self._meta_area_where_entry = tc()
    # 执行SQL语句
    self._runsql_area = wx.StaticBox()
    self._runsql_area_sql_query_ckbtn = cb()
    self._runsql_area_sql_query_entry = tc()
    self._runsql_area_sql_shell_ckbtn = cb()
    self._runsql_area_sql_file_ckbtn = cb()
    self._runsql_area_sql_file_entry = tc()
    self._runsql_area_sql_file_chooser = btn()
    # 暴破表名/列名
    self._brute_force_area = wx.StaticBox()
    self._brute_force_area_common_tables_ckbtn = cb()
    self._brute_force_area_common_columns_ckbtn = cb()
    self._brute_force_area_common_files_ckbtn = cb()
  # 文件(R)
    # 读取远程文件
    self._file_read_area = wx.StaticBox()
    self._file_read_area_file_read_ckbtn = cb()
    self._file_read_area_file_read_entry = tc()
    self._file_read_area_file_read_btn = btn()
    # 文件上传
    self._file_write_area = wx.StaticBox()
    self._file_write_area_udf_ckbtn = cb()
    self._file_write_area_shared_lib_ckbtn = cb()
    self._file_write_area_shared_lib_entry = tc()
    self._file_write_area_shared_lib_chooser = btn()
    self._file_write_area_file_write_ckbtn = cb()
    self._file_write_area_file_write_entry = tc()
    self._file_write_area_file_write_chooser = btn()
    self._file_write_area_file_dest_ckbtn = cb()
    self._file_write_area_file_dest_entry = tc()
    # 访问后端OS
    self._file_os_access_area = wx.StaticBox()
    self._file_os_access_os_cmd_ckbtn = cb()
    self._file_os_access_os_cmd_entry = tc()
    self._file_os_access_os_shell_ckbtn = cb()
    self._file_os_access_os_pwn_ckbtn = cb()
    self._file_os_access_os_smbrelay_ckbtn = cb()
    self._file_os_access_os_bof_ckbtn = cb()
    self._file_os_access_priv_esc_ckbtn = cb()
    self._file_os_access_msf_path_ckbtn = cb()
    self._file_os_access_msf_path_entry = tc()
    self._file_os_access_msf_path_chooser = btn()
    self._file_os_access_tmp_path_ckbtn = cb()
    self._file_os_access_tmp_path_entry = tc()
    # 访问WIN下注册表
    self._file_os_registry_area = wx.StaticBox()
    self._file_os_registry_reg_ckbtn = cb()
    self._file_os_registry_reg_choice = ci()
    self._file_os_registry_reg_key_label = st()
    self._file_os_registry_reg_key_entry = tc()
    self._file_os_registry_reg_value_label = st()
    self._file_os_registry_reg_value_entry = tc()
    self._file_os_registry_reg_data_label = st()
    self._file_os_registry_reg_data_entry = tc()
    self._file_os_registry_reg_type_label = st()
    self._file_os_registry_reg_type_entry = tc()
  # 其他(T)
    # 通用项
    self._page1_other_general_area = wx.StaticBox()
    self._page1_general_check_internet_ckbtn = cb()
    self._page1_general_fresh_queries_ckbtn = cb()
    self._page1_general_forms_ckbtn = cb()
    self._page1_general_parse_errors_ckbtn = cb()
    self._page1_misc_cleanup_ckbtn = cb()
    self._page1_general_table_prefix_ckbtn = cb()
    self._page1_general_table_prefix_entry = tc()
    self._page1_general_binary_fields_ckbtn = cb()
    self._page1_general_binary_fields_entry = tc()
    self._page1_general_preprocess_ckbtn = cb()
    self._page1_general_preprocess_entry = tc()
    self._page1_general_preprocess_chooser = btn()
    self._page1_general_charset_ckbtn = cb()
    self._page1_general_charset_entry = tc()
    self._page1_general_encoding_ckbtn = cb()
    self._page1_general_encoding_entry = tc()
    self._page1_general_web_root_ckbtn = cb()
    self._page1_general_web_root_entry = tc()
    self._page1_general_scope_ckbtn = cb()
    self._page1_general_scope_entry = tc()
    self._page1_general_scope_chooser = btn()
    self._page1_general_test_filter_ckbtn = cb()
    self._page1_general_test_filter_entry = tc()
    self._page1_general_test_skip_ckbtn = cb()
    self._page1_general_test_skip_entry = tc()
    self._page1_general_crawl_ckbtn = cb()
    self._page1_general_crawl_entry = nc()
    self._page1_general_crawl_exclude_ckbtn = cb()
    self._page1_general_crawl_exclude_entry = tc()
    self._page1_general_traffic_file_ckbtn = cb()
    self._page1_general_traffic_file_entry = tc()
    self._page1_general_traffic_file_chooser = btn()
    self._page1_general_har_ckbtn = cb()
    self._page1_general_har_entry = tc()
    self._page1_general_har_chooser = btn()
    self._page1_general_flush_session_ckbtn = cb()
    self._page1_general_dump_format_ckbtn = cb()
    self._page1_general_dump_format_entry = tc()
    self._page1_general_csv_del_ckbtn = cb()
    self._page1_general_csv_del_entry = tc()
    self._page1_general_save_ckbtn = cb()
    self._page1_general_save_entry = tc()
    self._page1_general_save_chooser = btn()
    self._page1_general_session_file_ckbtn = cb()
    self._page1_general_session_file_entry = tc()
    self._page1_general_session_file_chooser = btn()
    self._page1_general_output_dir_ckbtn = cb()
    self._page1_general_output_dir_entry = tc()
    self._page1_general_output_dir_chooser = btn()
    # 杂项
    self._page1_other_misc_area = wx.StaticBox()
    self._page1_misc_skip_waf_ckbtn = cb()
    self._page1_misc_list_tampers_ckbtn = cb()
    self._page1_misc_sqlmap_shell_ckbtn = cb()
    self._page1_misc_disable_color_ckbtn = cb()
    self._page1_general_eta_ckbtn = cb()
    self._page1_misc_update_ckbtn = cb()
    self._page1_misc_gpage_ckbtn = cb()
    self._page1_misc_gpage_spinbtn = sp()
    self._page1_misc_beep_ckbtn = cb()
    self._page1_misc_offline_ckbtn = cb()
    self._page1_misc_purge_ckbtn = cb()
    self._page1_misc_dependencies_ckbtn = cb()
    self._page1_misc_alert_ckbtn = cb()
    self._page1_misc_alert_entry = tc()
    self._page1_misc_tmp_dir_ckbtn = cb()
    self._page1_misc_tmp_dir_entry = tc()
    self._page1_misc_tmp_dir_chooser = btn()
    self._page1_misc_answers_ckbtn = cb()
    self._page1_misc_answers_entry = tc()
    self._page1_misc_z_ckbtn = cb()
    self._page1_misc_z_entry = tc()


def main():
  pass


if __name__ == '__main__':
  main()
