#!/usr/bin/env python3
#
# 2019-10-13 00:00:33

from widgets import StaticBox, btn, cb, cbb, ci, nc, sl, sp, st, tc


class Model(object):
  def __init__(self, full = True):
    self._core()

    if full:
      self._outer()

  def _outer(self):
    # TARGET
    self._url_combobox = cbb()
    self._burp_logfile = tc()
    self._burp_logfile_chooser = btn()
    self._request_file = tc()
    self._request_file_chooser = btn()
    self._bulkfile = tc()
    self._bulkfile_chooser = btn()
    self._configfile = tc()
    self._configfile_chooser = btn()
    self._google_dork = tc()
    self._direct_connect = tc()
  # OPTIONS(1)
  # collected options:
    self._cmd_entry = tc()
  # self._core()...
  # EXECUTION(2)
  # LOG(3)
    self._page3_log_view = tc()
    self._page3_read_target_btn = btn()
    self._page3_clear_btn = btn()
    self._page3_read_log_btn = btn()
  # SQLMAPAPI(4)
    self._page4_api_server_label = st()
    self._page4_api_server_entry = tc()
    self._page4_admin_token_label = st()
    self._page4_admin_token_entry = tc()
    self._page4_task_new_btn = btn()
    self._page4_admin_list_btn = btn()
    self._page4_admin_flush_btn = btn()
    self._page4_clear_task_view_btn = btn()
    self._page4_username_label = st()
    self._page4_username_entry = tc()
    self._page4_password_label = st()
    self._page4_password_entry = tc()
    self._page4_option_get_entry = tc()
    self._page4_option_set_view = tc()
    self._page4_task_view = tc()
  # HELP(H)
    self._page5_manual_view = tc()
  # ABOUT

  def _core(self):
    pass
  # Inject(Q)
    self._sqlmap_path_label = st()
    self.sqlmap_path_entry = tc()
    self._sqlmap_path_chooser = btn()
    # Injection
    self._inject_area = StaticBox()
    self._inject_area_param_ckbtn = cb()
    self._inject_area_param_entry = tc()
    self._inject_area_param_filter_ckbtn = cb()
    self._inject_area_param_filter_combobox = cbb()
    self._inject_area_skip_static_ckbtn = cb()
    self._inject_area_skip_ckbtn = cb()
    self._inject_area_skip_entry = tc()
    self._inject_area_param_exclude_ckbtn = cb()
    self._inject_area_param_exclude_entry = tc()
    self._inject_area_prefix_ckbtn = cb()
    self._inject_area_prefix_entry = tc()
    self._inject_area_suffix_ckbtn = cb()
    self._inject_area_suffix_entry = tc()
    self._inject_area_dbms_ckbtn = cb()
    self._inject_area_dbms_combobox = cbb()
    self._inject_area_dbms_cred_ckbtn = cb()
    self._inject_area_dbms_cred_entry = tc()
    self._inject_area_os_ckbtn = cb()
    self._inject_area_os_entry = tc()
    self._inject_area_no_cast_ckbtn = cb()
    self._inject_area_no_escape_ckbtn = cb()
    self._inject_area_invalid_bignum_ckbtn = cb()
    self._inject_area_invalid_logic_ckbtn = cb()
    self._inject_area_invalid_string_ckbtn = cb()
    # Detection
    self._detection_area = StaticBox()
    self._detection_area_level_ckbtn = cb()
    self._detection_area_level_scale = sl()
    self._detection_area_risk_ckbtn = cb()
    self._detection_area_risk_scale = sl()
    self._detection_area_str_ckbtn = cb()
    self._detection_area_str_entry = tc()
    self._detection_area_not_str_ckbtn = cb()
    self._detection_area_not_str_entry = tc()
    self._detection_area_re_ckbtn = cb()
    self._detection_area_re_entry = tc()
    self._detection_area_code_ckbtn = cb()
    self._detection_area_code_entry = nc()
    self._detection_area_text_only_ckbtn = cb()
    self._detection_area_titles_ckbtn = cb()
    self._detection_area_smart_ckbtn = cb()
    # Technique
    self._tech_area = StaticBox()
    self._tech_area_tech_ckbtn = cb()
    self._tech_area_tech_entry = tc()
    self._tech_area_time_sec_ckbtn = cb()
    self._tech_area_time_sec_entry = nc()
    self._tech_area_union_col_ckbtn = cb()
    self._tech_area_union_col_entry = nc()
    self._tech_area_union_char_ckbtn = cb()
    self._tech_area_union_char_entry = tc()
    self._tech_area_union_from_ckbtn = cb()
    self._tech_area_union_from_entry = tc()
    self._tech_area_dns_ckbtn = cb()
    self._tech_area_dns_entry = tc()
    self._tech_area_second_url_ckbtn = cb()
    self._tech_area_second_url_entry = tc()
    self._tech_area_second_req_ckbtn = cb()
    self._tech_area_second_req_entry = tc()
    self._tech_area_second_req_chooser = btn()
    # Tamper
    self._tamper_area = StaticBox()
    self._tamper_area_tamper_view = tc()
    # Optimize
    self._optimize_area = StaticBox()
    self._optimize_area_turn_all_ckbtn = cb()
    self._optimize_area_thread_num_ckbtn = cb()
    self._optimize_area_thread_num_spinbtn = sp()
    self._optimize_area_predict_ckbtn = cb()
    self._optimize_area_keep_alive_ckbtn = cb()
    self._optimize_area_null_connect_ckbtn = cb()
    # Offen
    self._offen_area = StaticBox()
    self._general_area_verbose_ckbtn = cb()
    self._general_area_verbose_scale = sl()
    self._general_area_finger_ckbtn = cb()
    self._general_area_hex_ckbtn = cb()
    self._general_area_batch_ckbtn = cb()
    self._misc_area_wizard_ckbtn = cb()
    # Hidden
  # Request(W)
    # HTTP header
    self._request_header_area = StaticBox()
    self._request_area_random_agent_ckbtn = cb()
    self._request_area_mobile_ckbtn = cb()
    self._request_area_user_agent_ckbtn = cb()
    self._request_area_user_agent_entry = tc()
    self._request_area_host_ckbtn = cb()
    self._request_area_host_entry = tc()
    self._request_area_referer_ckbtn = cb()
    self._request_area_referer_entry = tc()
    self._request_area_header_ckbtn = cb()
    self._request_area_header_entry = tc()
    self._request_area_headers_ckbtn = cb()
    self._request_area_headers_entry = tc()
    # HTTP data
    self._request_data_area = StaticBox()
    self._request_area_method_ckbtn = cb()
    self._request_area_method_entry = tc()
    self._request_area_param_del_ckbtn = cb()
    self._request_area_param_del_entry = tc()
    self._request_area_chunked_ckbtn = cb()
    self._request_area_post_ckbtn = cb()
    self._request_area_post_entry = tc()
    self._request_area_cookie_ckbtn = cb()
    self._request_area_cookie_entry = tc()
    self._request_area_cookie_del_ckbtn = cb()
    self._request_area_cookie_del_entry = tc()
    self._request_area_drop_set_cookie_ckbtn = cb()
    self._request_area_live_cookies_ckbtn = cb()
    self._request_area_live_cookies_entry = tc()
    self._request_area_live_cookies_chooser = btn()
    self._request_area_load_cookies_ckbtn = cb()
    self._request_area_load_cookies_entry = tc()
    self._request_area_load_cookies_chooser = btn()
    self._request_area_auth_type_ckbtn = cb()
    self._request_area_auth_type_entry = tc()
    self._request_area_auth_cred_ckbtn = cb()
    self._request_area_auth_cred_entry = tc()
    self._request_area_auth_file_ckbtn = cb()
    self._request_area_auth_file_entry = tc()
    self._request_area_auth_file_chooser = btn()
    self._request_area_csrf_method_ckbtn = cb()
    self._request_area_csrf_method_entry = tc()
    self._request_area_csrf_retries_ckbtn = cb()
    self._request_area_csrf_retries_entry = nc()
    self._request_area_csrf_token_ckbtn = cb()
    self._request_area_csrf_token_entry = tc()
    self._request_area_csrf_url_ckbtn = cb()
    self._request_area_csrf_url_entry = tc()
    # Request custom
    self._request_custom_area = StaticBox()
    self._request_area_ignore_timeouts_ckbtn = cb()
    self._request_area_ignore_redirects_ckbtn = cb()
    self._request_area_ignore_code_ckbtn = cb()
    self._request_area_ignore_code_entry = tc()
    self._request_area_skip_urlencode_ckbtn = cb()
    self._request_area_force_ssl_ckbtn = cb()
    self._request_area_hpp_ckbtn = cb()
    self._request_area_delay_ckbtn = cb()
    self._request_area_delay_entry = nc()
    self._request_area_timeout_ckbtn = cb()
    self._request_area_timeout_entry = nc()
    self._request_area_retries_ckbtn = cb()
    self._request_area_retries_entry = nc()
    self._request_area_randomize_ckbtn = cb()
    self._request_area_randomize_entry = tc()
    self._request_area_eval_ckbtn = cb()
    self._request_area_eval_entry = tc()
    # Anonymous/Proxy
    self._request_proxy_area = StaticBox()
    self._request_area_safe_url_ckbtn = cb()
    self._request_area_safe_url_entry = tc()
    self._request_area_safe_post_ckbtn = cb()
    self._request_area_safe_post_entry = tc()
    self._request_area_safe_req_ckbtn = cb()
    self._request_area_safe_req_entry = tc()
    self._request_area_safe_req_chooser = btn()
    self._request_area_safe_freq_ckbtn = cb()
    self._request_area_safe_freq_entry = tc()
    self._request_area_ignore_proxy_ckbtn = cb()
    self._request_area_proxy_freq_ckbtn = cb()
    self._request_area_proxy_freq_entry = nc()
    self._request_area_proxy_file_ckbtn = cb()
    self._request_area_proxy_file_entry = tc()
    self._request_area_proxy_file_chooser = btn()
    self._request_area_proxy_ckbtn = cb()
    self._request_area_proxy_ip_label = st()
    self._request_area_proxy_ip_entry = tc()
    self._request_area_proxy_port_label = st()
    self._request_area_proxy_port_entry = nc()
    self._request_area_proxy_username_label = st()
    self._request_area_proxy_username_entry = tc()
    self._request_area_proxy_password_label = st()
    self._request_area_proxy_password_entry = tc()
    self._request_area_tor_ckbtn = cb()
    self._request_area_tor_port_ckbtn = cb()
    self._request_area_tor_port_entry = nc()
    self._request_area_tor_type_ckbtn = cb()
    self._request_area_tor_type_entry = tc()
    self._request_area_check_tor_ckbtn = cb()
  # Enumerate(E)
    # Enumeration
    self._enum_area = StaticBox()
    # 要求要与_enum_area_enum_labels的结构一致!
    self._enum_area_opts_ckbtns = [[cb() for _ in range(5)] for _r in range(3)]
    # Dump
    self._dump_area = StaticBox()
    self._dump_area_dump_ckbtn = cb()
    self._dump_area_repair_ckbtn = cb()
    self._dump_area_statements_ckbtn = cb()
    self._dump_area_search_ckbtn = cb()
    self._dump_area_no_sys_db_ckbtn = cb()
    self._dump_area_dump_all_ckbtn = cb()
    # Limit(when dump)
    self._limit_area = StaticBox()
    self._limit_area_start_ckbtn = cb()
    self._limit_area_start_entry = nc()
    self._limit_area_stop_ckbtn = cb()
    self._limit_area_stop_entry = nc()
    # Blind inject options
    self._blind_area = StaticBox()
    self._blind_area_first_ckbtn = cb()
    self._blind_area_first_entry = nc()
    self._blind_area_last_ckbtn = cb()
    self._blind_area_last_entry = nc()
    # DB, Table, Column name...
    self._meta_area = StaticBox()
    self._meta_area_D_ckbtn = cb()
    self._meta_area_D_entry = tc()
    self._meta_area_T_ckbtn = cb()
    self._meta_area_T_entry = tc()
    self._meta_area_C_ckbtn = cb()
    self._meta_area_C_entry = tc()
    self._meta_area_U_ckbtn = cb()
    self._meta_area_U_entry = tc()
    self._meta_area_X_ckbtn = cb()
    self._meta_area_X_entry = tc()
    self._meta_area_pivot_ckbtn = cb()
    self._meta_area_pivot_entry = tc()
    self._meta_area_where_ckbtn = cb()
    self._meta_area_where_entry = tc()
    # Execute SQL
    self._runsql_area = StaticBox()
    self._runsql_area_sql_query_ckbtn = cb()
    self._runsql_area_sql_query_entry = tc()
    self._runsql_area_sql_shell_ckbtn = cb()
    self._runsql_area_sql_file_ckbtn = cb()
    self._runsql_area_sql_file_entry = tc()
    self._runsql_area_sql_file_chooser = btn()
    # Brute force
    self._brute_force_area = StaticBox()
    self._brute_force_area_common_tables_ckbtn = cb()
    self._brute_force_area_common_columns_ckbtn = cb()
    self._brute_force_area_common_files_ckbtn = cb()
  # File(R)
    # Read remote file
    self._file_read_area = StaticBox()
    self._file_read_area_file_read_ckbtn = cb()
    self._file_read_area_file_read_entry = tc()
    self._file_read_area_file_read_btn = btn()
    # Upload local file
    self._file_write_area = StaticBox()
    self._file_write_area_udf_ckbtn = cb()
    self._file_write_area_shared_lib_ckbtn = cb()
    self._file_write_area_shared_lib_entry = tc()
    self._file_write_area_shared_lib_chooser = btn()
    self._file_write_area_file_write_ckbtn = cb()
    self._file_write_area_file_write_entry = tc()
    self._file_write_area_file_write_chooser = btn()
    self._file_write_area_file_dest_ckbtn = cb()
    self._file_write_area_file_dest_entry = tc()
    # Access to the OS behind the DBMS
    self._os_access_area = StaticBox()
    self._os_access_area_os_cmd_ckbtn = cb()
    self._os_access_area_os_cmd_entry = tc()
    self._os_access_area_os_shell_ckbtn = cb()
    self._os_access_area_os_pwn_ckbtn = cb()
    self._os_access_area_os_smbrelay_ckbtn = cb()
    self._os_access_area_os_bof_ckbtn = cb()
    self._os_access_area_priv_esc_ckbtn = cb()
    self._os_access_area_msf_path_ckbtn = cb()
    self._os_access_area_msf_path_entry = tc()
    self._os_access_area_msf_path_chooser = btn()
    self._os_access_area_tmp_path_ckbtn = cb()
    self._os_access_area_tmp_path_entry = tc()
    # Access to register in remote WIN
    self._registry_area = StaticBox()
    self._registry_area_reg_ckbtn = cb()
    self._registry_area_reg_choice = ci()
    self._registry_area_reg_key_label = st()
    self._registry_area_reg_key_entry = tc()
    self._registry_area_reg_value_label = st()
    self._registry_area_reg_value_entry = tc()
    self._registry_area_reg_data_label = st()
    self._registry_area_reg_data_entry = tc()
    self._registry_area_reg_type_label = st()
    self._registry_area_reg_type_entry = tc()
  # Other(T)
    # General
    self._general_area = StaticBox()
    self._general_area_check_internet_ckbtn = cb()
    self._general_area_fresh_queries_ckbtn = cb()
    self._general_area_forms_ckbtn = cb()
    self._general_area_parse_errors_ckbtn = cb()
    self._misc_area_cleanup_ckbtn = cb()
    self._general_area_base64_ckbtn = cb()
    self._general_area_base64_entry = tc()
    self._general_area_base64_safe_ckbtn = cb()
    self._general_area_table_prefix_ckbtn = cb()
    self._general_area_table_prefix_entry = tc()
    self._general_area_binary_fields_ckbtn = cb()
    self._general_area_binary_fields_entry = tc()
    self._general_area_preprocess_ckbtn = cb()
    self._general_area_preprocess_entry = tc()
    self._general_area_preprocess_chooser = btn()
    self._general_area_postprocess_ckbtn = cb()
    self._general_area_postprocess_entry = tc()
    self._general_area_postprocess_chooser = btn()
    self._general_area_charset_ckbtn = cb()
    self._general_area_charset_entry = tc()
    self._general_area_encoding_ckbtn = cb()
    self._general_area_encoding_entry = tc()
    self._general_area_web_root_ckbtn = cb()
    self._general_area_web_root_entry = tc()
    self._general_area_scope_ckbtn = cb()
    self._general_area_scope_entry = tc()
    self._general_area_scope_chooser = btn()
    self._general_area_test_filter_ckbtn = cb()
    self._general_area_test_filter_entry = tc()
    self._general_area_test_skip_ckbtn = cb()
    self._general_area_test_skip_entry = tc()
    self._general_area_crawl_ckbtn = cb()
    self._general_area_crawl_entry = nc()
    self._general_area_crawl_exclude_ckbtn = cb()
    self._general_area_crawl_exclude_entry = tc()
    self._general_area_traffic_file_ckbtn = cb()
    self._general_area_traffic_file_entry = tc()
    self._general_area_traffic_file_chooser = btn()
    self._general_area_har_ckbtn = cb()
    self._general_area_har_entry = tc()
    self._general_area_har_chooser = btn()
    self._general_area_flush_session_ckbtn = cb()
    self._general_area_dump_format_ckbtn = cb()
    self._general_area_dump_format_entry = tc()
    self._general_area_csv_del_ckbtn = cb()
    self._general_area_csv_del_entry = tc()
    self._general_area_save_ckbtn = cb()
    self._general_area_save_entry = tc()
    self._general_area_save_chooser = btn()
    self._general_area_session_file_ckbtn = cb()
    self._general_area_session_file_entry = tc()
    self._general_area_session_file_chooser = btn()
    self._general_area_output_dir_ckbtn = cb()
    self._general_area_output_dir_entry = tc()
    self._general_area_output_dir_chooser = btn()
    # Misc
    self._misc_area = StaticBox()
    self._misc_area_skip_heuristics_ckbtn = cb()
    self._misc_area_skip_waf_ckbtn = cb()
    self._misc_area_unstable_ckbtn = cb()
    self._misc_area_list_tampers_ckbtn = cb()
    self._misc_area_sqlmap_shell_ckbtn = cb()
    self._misc_area_disable_color_ckbtn = cb()
    self._general_area_eta_ckbtn = cb()
    self._misc_area_gpage_ckbtn = cb()
    self._misc_area_gpage_spinbtn = sp()
    self._misc_area_beep_ckbtn = cb()
    self._misc_area_offline_ckbtn = cb()
    self._misc_area_purge_ckbtn = cb()
    self._misc_area_dependencies_ckbtn = cb()
    self._misc_area_update_ckbtn = cb()
    self._misc_area_alert_ckbtn = cb()
    self._misc_area_alert_entry = tc()
    self._misc_area_tmp_dir_ckbtn = cb()
    self._misc_area_tmp_dir_entry = tc()
    self._misc_area_tmp_dir_chooser = btn()
    self._misc_area_answers_ckbtn = cb()
    self._misc_area_answers_entry = tc()
    self._misc_area_z_ckbtn = cb()
    self._misc_area_z_entry = tc()
    self._misc_area_results_file_ckbtn = cb()
    self._misc_area_results_file_entry = tc()
    self._misc_area_results_file_chooser = btn()


def main():
  pass


if __name__ == '__main__':
  main()
